## Práctica 33 
### Broadcasting

Ejecutar todos los códigos y el ejemplo práctico de la documentación oficial de Numpy  sobre Broadcasting en un 'Notebook de Jupyter'. Traducir también la teoría y pegarla en celdas de texto.

https://numpy.org/doc/stable/user/basics.broadcasting.html

* Transmisión o Radiodifusión == Broadcasting

El término transmisión describe cómo NumPy trata matrices con diferentes formas durante operaciones aritméticas. Sujeto a ciertas restricciones, la matriz más pequeña se "difunde" a través de la matriz más grande para que tengan formas compatibles. La transmisión proporciona un medio para vectorizar operaciones de matrices para que el bucle se produzca en C en lugar de Python. Lo hace sin realizar copias innecesarias de datos y, por lo general, conduce a implementaciones de algoritmos eficientes. Sin embargo, hay casos en los que la transmisión es una mala idea porque conduce a un uso ineficiente de la memoria que ralentiza el cálculo.

Las operaciones NumPy generalmente se realizan en pares de matrices elemento por elemento. En el caso más simple, las dos matrices deben tener exactamente la misma forma, como en el siguiente ejemplo:

In [1]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

La regla de transmisión de NumPy relaja esta restricción cuando las formas de las matrices cumplen ciertas restricciones. El ejemplo de transmisión más simple ocurre cuando se combinan una matriz y un valor escalar en una operación:

In [2]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

El resultado es equivalente al ejemplo anterior donde 'b' había una matriz. Podemos imaginar que el escalar 'b' se estira durante la operación aritmética hasta formar una matriz con la misma forma que 'a'. Los nuevos elementos en 'b', como se muestra en la Figura 1 , son simplemente copias del escalar original. La analogía del estiramiento es sólo conceptual. NumPy es lo suficientemente inteligente como para usar el valor escalar original sin hacer copias, de modo que las operaciones de transmisión sean lo más eficientes posible en memoria y computación.

Se transmite un escalar para que coincida con la forma de la matriz unidimensional por la que se está multiplicando.

Figura 1

En el ejemplo más simple de transmisión, el escalar b se estira para convertirse en una matriz de la misma forma, de a modo que las formas sean compatibles para la multiplicación elemento por elemento.

El código del segundo ejemplo es más eficiente que el del primero porque la transmisión mueve menos memoria durante la multiplicación ( bes un escalar en lugar de una matriz).

### Normas generales de retransmisión 
Cuando opera en dos matrices, NumPy compara sus formas por elementos. Comienza con la dimensión final (es decir, la más a la derecha) y avanza hacia la izquierda. Dos dimensiones son compatibles cuando

 1. son iguales, o

 2. uno de ellos es 1.

Si no se cumplen estas condiciones, se genera una excepción que indica que las matrices tienen formas incompatibles.    ValueError: operands could not be broadcast together

No es necesario que las matrices de entrada tengan la misma cantidad de dimensiones. La matriz resultante tendrá la misma cantidad de dimensiones que la matriz de entrada con la mayor cantidad de dimensiones, donde el tamaño de cada dimensión es el tamaño más grande de la dimensión correspondiente entre las matrices de entrada. Tenga en cuenta que se supone que las dimensiones que faltan tienen el tamaño uno.

Por ejemplo, si tiene una 256x256x3 matriz de valores RGB y desea escalar cada color de la imagen con un valor diferente, puede multiplicar la imagen por una matriz unidimensional con 3 valores. Alinear los tamaños de los ejes posteriores de estos arreglos de acuerdo con las reglas de transmisión muestra que son compatibles:



Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

Cuando alguna de las dimensiones comparadas es una, se utiliza la otra. En otras palabras, las dimensiones con tamaño 1 se estiran o “copian” para que coincidan con las otras.

En el siguiente ejemplo, tanto las matrices A como B tienen ejes con longitud uno que se expanden a un tamaño mayor durante la operación de transmisión:

| **Matrices**      | **Dimensiones**    |
|-------------------|--------------------|
| A (4d array)      | 8 x 1 x 6 x 1      |
| B (3d array)      | 7 x 1 x 5          |
| Result (4d array) | 8 x 7 x 6 x 5      |


### Matrices transmitibles 
Un conjunto de matrices se denomina "transmisible" a la misma forma si las reglas anteriores producen un resultado válido.

Por ejemplo, si a.shapees (5,1), b.shapees (1,6), c.shapees (6,) y d.shapees () de modo que d es un escalar, entonces a , b , c y d se pueden transmitir a la dimensión (5 ,6); y

    - a actúa como una matriz (5,6) donde a[:,0]se transmite a las otras columnas,

    - b actúa como una matriz (5,6) donde b[0,:]se transmite a las otras filas,

    - c actúa como una matriz (1,6) y por lo tanto como una matriz (5,6) donde c[:]se transmite a cada fila, y finalmente,

    - d actúa como una matriz (5,6) donde se repite el valor único.

Aquí hay algunos ejemplos más:

| **A (Array)**  | **Filas x Columnas A** | **B (Array)**  | **Filas x Columnas B** | **Result (Array)**  | **Filas x Columnas Result** |
|----------------|-------------------|----------------|-------------------|---------------------|------------------------|
| 2d array       | 5 x 4             | 1d array       | 1                 | 2d array            | 5 x 4                  |
| 2d array       | 5 x 4             | 1d array       | 4                 | 2d array            | 5 x 4                  |
| 3d array       | 15 x 3 x 5        | 3d array       | 15 x 1 x 5        | 3d array            | 15 x 3 x 5             |
| 3d array       | 15 x 3 x 5        | 2d array       | 3 x 5             | 3d array            | 15 x 3 x 5             |
| 3d array       | 15 x 3 x 5        | 2d array       | 3 x 1             | 3d array            | 15 x 3 x 5             |


A continuación se muestran ejemplos de formas que no se transmiten:

| **Nombre**         | **Filas x Columnas**                      | **Notas**                                  |
|--------------------|--------------------------------------|--------------------------------------------|
| A (1d array)       | 3                                    |                                            |
| B (1d array)       | 4                                    | trailing dimensions do not match           |
| A (2d array)       | 2 x 1                                |                                            |
| B (3d array)       | 8 x 4 x 3                            | second from last dimensions mismatched     |


Un ejemplo de transmisión cuando se agrega una matriz unidimensional a una matriz bidimensional:

In [4]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [5]:
b = np.array([1.0, 2.0, 3.0, 4.0])
a + b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

Como se muestra en la Figura 2 , bse agrega a cada fila de a. En la Figura 3 , se plantea una excepción debido a las formas incompatibles.

Una matriz 1-d con forma (3) se estira para que coincida con la matriz 2-d de forma (4, 3) a la que se está agregando, y el resultado es una matriz 2-d de forma (4, 3).
Figura 2

Una matriz unidimensional agregada a una matriz bidimensional da como resultado una transmisión si el número de elementos de la matriz unidimensional coincide con el número de columnas de la matriz bidimensional.
Una gran cruz sobre la matriz de formas bidimensional (4, 3) y la matriz de formas unidimensional (4) muestra que no se pueden transmitir debido a la falta de coincidencia de formas y, por lo tanto, no producen ningún resultado.

figura 3

Cuando las dimensiones finales de las matrices son desiguales, la transmisión falla porque es imposible alinear los valores en las filas de la primera matriz con los elementos de la segunda matriz para la suma elemento por elemento.

La radiodifusión proporciona una manera conveniente de tomar el producto exterior (o cualquier otra operación exterior) de dos matrices. El siguiente ejemplo muestra una operación de suma externa de dos matrices unidimensionales:

In [6]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

Una matriz de formas bidimensional (4, 1) y una matriz de formas unidimensional (3) se estiran para que coincidan con sus formas y produzcan una matriz de formas resultante (4, 3).

Figura 4

En algunos casos, la difusión extiende ambas matrices para formar una matriz de salida más grande que cualquiera de las matrices iniciales.

Aquí el newaxis operador de índice inserta un nuevo eje en a, convirtiéndolo en una matriz bidimensional 4x1. Combinando la 4x1 matriz con b, que tiene forma (3,), se obtiene una 4x3 matriz.

### práctico: cuantificación vectorial

La radiodifusión surge con bastante frecuencia en los problemas del mundo real. Un ejemplo típico ocurre en el algoritmo de cuantificación vectorial (VQ) utilizado en teoría de la información, clasificación y otras áreas relacionadas. La operación básica en VQ encuentra el punto más cercano en un conjunto de puntos, llamado codes en la jerga VQ, a un punto dado, llamado observation. En el caso bidimensional muy simple que se muestra a continuación, los valores observation describen el peso y la altura de un atleta que se va a clasificar. Representan codes diferentes clases de atletas. [ 1 ] Encontrar el punto más cercano requiere calcular la distancia entre la observación y cada uno de los códigos. La distancia más corta proporciona la mejor coincidencia. En este ejemplo, codes[0] la clase más cercana indica que el atleta probablemente sea un jugador de baloncesto.

In [7]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
argmin(dist)

np.int64(0)

En este ejemplo, la observation matriz se estira para que coincida con la forma de la codes matriz:

| **Array**       | **Filas x Columnas** |
|------------------|-----------------|
| Observation (1d array) | 2           |
| Codes (2d array)       | 4 x 2       |
| Diff (2d array)        | 4 x 2       |


Un gráfico de altura versus peso que muestra datos de una gimnasta, corredora de maratón, jugadora de baloncesto, liniero de fútbol y el atleta a clasificar. La distancia más corta se encuentra entre el jugador de baloncesto y el deportista a clasificar.

Figura 5

La operación básica de la cuantificación vectorial calcula la distancia entre un objeto a clasificar, el cuadrado oscuro, y múltiples códigos conocidos, los círculos grises. En este caso sencillo, los códigos representan clases individuales. Los casos más complejos utilizan varios códigos por clase.

Normalmente, una gran cantidad de archivos observations, quizás leídos de una base de datos, se comparan con un conjunto de archivos codes. Considere este escenario:

| **Array**     | **Filas x Columnas** |
|----------------|------------------|
| Observation (2d array) | 10 x 3   |
| Codes (3d array)       | 5 x 1 x 3 |
| Diff (3d array)        | 5 x 10 x 3 |


La matriz tridimensional, diff, es una consecuencia de la radiodifusión, no una necesidad para el cálculo. Grandes conjuntos de datos generarán una gran matriz intermedia que es computacionalmente ineficiente. En cambio, si cada observación se calcula individualmente usando un bucle de Python alrededor del código en el ejemplo bidimensional anterior, se usa una matriz mucho más pequeña.

La transmisión es una herramienta poderosa para escribir código breve y generalmente intuitivo que realiza sus cálculos de manera muy eficiente en C. Sin embargo, hay casos en los que la transmisión utiliza cantidades innecesariamente grandes de memoria para un algoritmo en particular. En estos casos, es mejor escribir el bucle externo del algoritmo en Python. Esto también puede producir un código más legible, ya que los algoritmos que utilizan la transmisión tienden a volverse más difíciles de interpretar a medida que aumenta el número de dimensiones en la transmisión.

#### Notas a pie de página


En este ejemplo, el peso tiene más impacto en el cálculo de la distancia que la altura debido a los valores mayores. En la práctica, es importante normalizar la altura y el peso, a menudo mediante su desviación estándar en todo el conjunto de datos, de modo que ambos tengan la misma influencia en el cálculo de la distancia.